# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration Jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      # Ensure that we don't do a CRLF conversion on Windows
      - name: Disable CRLF conversions
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # Clone the repository
      - uses: actions/checkout@v2

      # Set up Node and yarn; use cached dependencies
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn install --frozen-lockfile
      - run: yarn check:prettier
      - run: yarn generate:langfile
      - run: yarn test
